#pragma once

#define USER_EVENT_FLAG_FREE_DATA1 0x10000000
#define USER_EVENT_FLAG_FREE_DATA2 0x20000000

#define USER_INPUT_CONTROLLERDB_UPDATED 101

#define USER_STREAM_CONNECTING 110
#define USER_STREAM_OPEN 111
#define USER_STREAM_CLOSE 118
#define USER_STREAM_FINISHED 119
#define USER_SIZE_CHANGED 150
#define USER_SHOW_HIDDEN_APPS (USER_EVENT_FLAG_FREE_DATA1 | USER_EVENT_FLAG_FREE_DATA2 | 160)

#define USER_OPEN_OVERLAY 531
#define USER_CLOSE_SOFT_KEYBOARD 532
#define USER_OPEN_SOFT_KEYBOARD 533
#define USER_TOGGLE_STATS_PIN 534
#define USER_CLOSE_HID_PANEL 535
#define USER_APP_FOREGROUND 536


extern unsigned int app_userevent_remotebutton;

#define USER_REMOTEBUTTONEVENT app_userevent_remotebutton